apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component-425252
  description: test-component
  annotations:
    github.com/project-slug: shmidt-i-test/another-test-0231253674
    backstage.io/techdocs-ref: github:https://github.com/shmidt-i-test/another-test-0231253674
spec:
  type: website
  lifecycle: experimental
  owner: guest
